### ISSUE TITLE
Incorrect date in document

### ISSUE THREAD

**Issue by ApproximateIdentity** [HistoryAtState/frus#1]
In document d451 in frus1955-57v21.xml the year in the date is 19575 when it should really be 1957. This can be found on line 14518.

Sorry if this isn't the right place to report this...

**Comment by joewiz** [comment]
@ApproximateIdentity Thank you again for your feedback. If you are still working on this project, we would welcome targeted pull requests fixing typos, and will review them. I am going to close this issue for now, so if you have additional questions, please let us know via an issue or PR.
