### ISSUE TITLE
Missing PNG images for frus1981-88v06

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/frus#101]
The static.history.state.gov bucket's `/frus/frus1981-88v06/tiff` folder has all of the images for this volume (0001-0728.tif), but the `medium` folder oddly starts with 1040.png and goes to 1305.png. So something must've gone wrong in the processing or upload of the PNGs for this volume.

Spotted and reported by @tuurma. Thanks for the report, Magdalena!

**Comment by mcdanielhn** [comment]
Split PDF into tiffs and pngs and re-uploaded all to S3 (0001-1305).
