### ISSUE TITLE
Bullets not rendering properly

### ISSUE THREAD

**Issue by awmarrs** [HistoryAtState/frus#114]
In this document:

https://history.state.gov/historicaldocuments/frus1961-63v20/d45

There appear to be bullets in front of the names of the attendees, but the bullets are showing up "on top of" the names rather than in front of them.

**Comment by seckroth** [comment]
@joewiz I found that adding /@type="participants" to both of the lists that are inside  list/@type="participants" here takes care of the problem, but would you prefer to handle this issue in rendering? There are more documents in the volume, and probably more volumes, with the same issue.
