### ISSUE TITLE
frus1920v03 corrupted page image

### ISSUE THREAD

**Issue by vak2ve** [HistoryAtState/frus#145]
<img width="554" alt="screen shot 2017-08-29 at 3 53 02 pm" src="https://user-images.githubusercontent.com/8865513/29841136-4b868114-8cd2-11e7-8981-3a9f8cfaee0a.png">

Docback of frus1920v03 mentions xml:id="pg-seq-0926-map-2". However multiple downloads of the S3 page images for this volume have 0926.tif as a 5kb file that won't open.

@joewiz is there a possibility that xml:id="pg-seq-0925-map-1" covers two pages and was mistakenly coded as two maps?

**Comment by joewiz** [comment]
Just for the record, Virginia and I confirmed that 0925 is the map, 0926 is the blank reverse face. I also ran `tiffinfo -D 0926.tif`, which confirmed the file is not corrupt - so it appears that the macOS Preview.app doesn't know how to read this image. This probably explains why Preview can't open other blank TIFF images. The tiffinfo tool is part of the libtiff package, which is included in the homebrew installer for imagemagick (which you'll have if you've gone through the instructions at https://github.com/HistoryAtState/hsg-project/wiki/Publishing-New-Volumes-to-Website#4-generate-tiffs-pngs-and-ebooks).
