### ISSUE TITLE
missing map in frus1902app1

### ISSUE THREAD

**Issue by vak2ve** [HistoryAtState/frus#167]
Facs 0265 and 0266 in this volume are missing from the page images downloaded from S3 and not in the 2015 or 2016 replacement folders. HCL indicates these pages were the front and blank back page of a map.

<img width="780" alt="screen shot 2017-12-04 at 12 05 42 pm" src="https://user-images.githubusercontent.com/8865513/33565689-d42dbf7c-d8eb-11e7-95e8-9cf30c086238.png">

Possible to rescan?

**Comment by joewiz** [comment]
@seckroth Would you be able to look into this missing image, by chance?

**Comment by seckroth** [comment]
Happy to. I’ll take a look at the images tomorrow and rescan if necessary.

**Comment by joewiz** [comment]
Super! Many thanks!

**Comment by vak2ve** [comment]
Thanks so much Stephanie!

**Comment by seckroth** [comment]
I just put the tif in S3 (renamed figure_0265). Would you mind making it a png?

**Comment by joewiz** [comment]
@vak2ve The directions are at https://github.com/HistoryAtState/hsg-project/wiki/preparing-volumes-for-digitization#crop-images. Let me know if you encounter any problems.

**Comment by vak2ve** [comment]
Great, thanks again Stephanie!
