### ISSUE TITLE
openers 

### ISSUE THREAD

**Issue by vak2ve** [HistoryAtState/frus#168]
Some bleeding of the segs into the first line of the doc, observed on localhost and on hsg. Not always present in other browsers (and never in ebooks) so not sure how much of this is unique to my experience. 

http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1906p2/d29
<img width="684" alt="screen shot 2017-12-04 at 12 44 37 pm" src="https://user-images.githubusercontent.com/8865513/33567388-06cad3e8-d8f1-11e7-89a2-0d26229e0f1c.png">

https://history.state.gov/historicaldocuments/frus1920v01/d364
<img width="691" alt="screen shot 2017-12-04 at 12 47 53 pm" src="https://user-images.githubusercontent.com/8865513/33567489-64c3fc86-d8f1-11e7-8827-2cb102116a9f.png">

Moving the seg above the dateline does fix this. Is there an automated way to switch those two elements globally in all affected files?

http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1906p2/d29
<img width="680" alt="screen shot 2017-12-04 at 12 52 03 pm" src="https://user-images.githubusercontent.com/8865513/33567666-f8752f04-d8f1-11e7-8680-7637e79a64b5.png">

**Comment by vak2ve** [comment]
@joewiz issue complete and closed.

**Comment by joewiz** [comment]
@vak2ve Excellent! Please submit a PR from https://github.com/HistoryAtState/frus/tree/fixes-for-issue-168, and I’ll merge it into master.
