### ISSUE TITLE
frus1969-76v42 XML and ebooks

### ISSUE THREAD

**Issue by mcdanielhn** [HistoryAtState/frus#178]
- [x] Passes FRUS TEI Schematron check
- [x] Passes RelaxNG schema check
- [ ] Scripts run
- [x] Upload the FRUS TEI file into localhost
- [x] Upload page images to S3
- [x] Typography and characters
- [x] Source note coding
- [x] Table of contents
- [x] Tables, both participant and other
- [x] Openers and assorted segs
- [ ] Datelines added and prepped for dates project
- [x] Front matter
- [x] Back matter
- [x] Random sample
- [x] Volume metadata
- [x] Ebook generation and review

**Comment by mcdanielhn** [comment]
-Corrected <editor> in ATS
-Italicized "Foreign Relations" in ATS
-Italicized "Historian" and added <lb> in Preface closer
-Verified cross references to Persons List

**Comment by joewiz** [comment]
@mcdanielhn Excellent! The volume looks great in its full, full text glory. 

@KerryHite Do you think it would be a good idea for HistoryAtState to send out a tweet to let the folks who already downloaded the PDF that the full, online, searchable version is now available?
