### ISSUE TITLE
Fix references to footnotes within footnotes

### ISSUE THREAD

**Issue by WaxCylinderRevival** [HistoryAtState/frus#187]
I frequently encounter the following issue:

1. From document A (example: https://history.state.gov/historicaldocuments/frus1969-76v38p2/d41), I find a reference to a footnote in Document B ("2. See footnote 2, Document 42.")
2. I click on the linked reference ("footnote 2, Document 42"), which brings me to https://history.state.gov/historicaldocuments/frus1969-76v38p2/d42fn2 rather than https://history.state.gov/historicaldocuments/frus1969-76v38p2/d42#fn2
3. When I manually correct for Document B#footnote (https://history.state.gov/historicaldocuments/frus1969-76v38p2/d42#fn2), the link does not bring me to the bookmarked footnote but, instead, to the top of Document B (https://history.state.gov/historicaldocuments/frus1969-76v38p2/d42#fn2 = https://history.state.gov/historicaldocuments/frus1969-76v38p2/d42)

**Comment by joewiz** [comment]
I think this issue is the same as the one described here: https://github.com/HistoryAtState/hsg-shell/issues/258.

**Comment by joewiz** [comment]
Fixed in https://github.com/HistoryAtState/hsg-shell/commit/87bf7788a6e9a27019ba3ac8a165dcc0da23adb1.
