### ISSUE TITLE
frus1951-54IranEd2 XML Review

### ISSUE THREAD

**Issue by mcdanielhn** [HistoryAtState/frus#242]
- [x] Passes FRUS TEI Schematron check
- [x] Passes RelaxNG schema check
- [x] Scripts run
- [x] Upload the FRUS TEI file into localhost
- [x] Upload page images to S3
- [x] Typography and characters
- [x] Source note coding
- [x] Table of contents
- [x] Tables, both participant and other
- [x] Openers and assorted segs
- [x] Datelines added and prepped for dates project
- [x] Postscripts and frus:attachments confirmed
- [x] Front matter
- [x] Back matter
- [x] Random sample
- [x] Volume metadata
- [x] Ebook generation and review

**Comment by mcdanielhn** [comment]
In progress.

**Comment by mcdanielhn** [comment]
On validation:

System ID: /Users/heather/workspace/hsg-project/repos/frus/volumes/frus1951-54IranEd2.xml
Main validation file: /Users/heather/workspace/hsg-project/repos/frus/volumes/frus1951-54IranEd2.xml
Scenario name: FRUS TEI + Secondary Review of Dates
Engine name: Jing
Severity: error
Description: element "xenoData" not allowed anywhere; expected the element end-tag or element "encodingDesc", "revisionDesc" or "xi:include"
Start location: 36:10
End location: 36:18

**Comment by joewiz** [comment]
Thanks for noting this, Heather! You can safely ignore this error ("element xenodata not allowed anywhere"). Our use of `<xenodata>` was a temporary way to handle certain volume-level metadata, and we have a plan to migrate this data to a more native TEI markup, so we will be addressing this in the near-to-mid term. cc @WaxCylinderRevival.

**Comment by WaxCylinderRevival** [comment]
Good observation, @mcdanielhn!  To echo Joe, please ignore this error.

(I almost ran a script to convert the xenoData but I didn't want to interfere with your publishing process.  Please let me know when publishing steps are complete.)
