### ISSUE TITLE
Doc 136 in 1947 vol. III

### ISSUE THREAD

**Issue by therealjameswilson** [HistoryAtState/frus#276]
https://history.state.gov/historicaldocuments/frus1947v03/d136

"It will foe necessary for the President and the Secretary of State"

I think original text may be:

"I will be necessary for the President and the Secretary of State"

**Comment by joewiz** [comment]
Indeed, [the scanned page image](https://history.state.gov/historicaldocuments/frus1947v03/pg_232) shows that this was an OCR mistake:

> [![Screen Shot 2020-06-29 at 3 09 16 PM](https://user-images.githubusercontent.com/59118/86046094-9e8a4800-ba1a-11ea-92d9-c43000ed91fc.png)](https://history.state.gov/historicaldocuments/frus1947v03/pg_232)

**Comment by joewiz** [comment]
@therealjameswilson Thanks for spotting that. It was quite a wide-ranging OCR glitch, as the commit shows: https://github.com/HistoryAtState/frus/commit/a1a59a3d8c6bc7a7c4709b9de18b62ab96019ebe

**Comment by therealjameswilson** [comment]
Nice!

**Comment by vak2ve** [comment]
Huge yikes! Thank you @therealjameswilson!
