### ISSUE TITLE
[frus] volume landing pages missing link to Madison

### ISSUE THREAD

**Issue by seckroth** [HistoryAtState/frus#33]
when no xml is available. Ex.https://history.state.gov/historicaldocuments/frus1875v01
![screen shot 2016-09-06 at 10 34 38 am](https://cloud.githubusercontent.com/assets/7490970/18277819/ceed259a-741d-11e6-933d-bb3096cee000.png)

**Comment by joewiz** [comment]
@seckroth Thanks for spotting this! I've fixed it. This was working on localhost, but I hadn't uploaded the revised "bibliography" files to hsg yet; now we're back in sync.
