### ISSUE TITLE
frus1977-80v11p1 d266 chart XML editing

### ISSUE THREAD

**Issue by vak2ve** [HistoryAtState/frus#333]
4-page chart in d266 needs XML editing. Should be 4-column table, possibly with nested tables

<img width="427" alt="Screenshot 2024-11-21 at 1 49 21 PM" src="https://github.com/user-attachments/assets/082ac1ab-259f-488c-98f8-6b36a14585e6">

Currently: 

<img width="730" alt="Screenshot 2024-11-21 at 1 51 59 PM" src="https://github.com/user-attachments/assets/d3bd2c36-05c9-473b-bbbb-158d843727af">

<img width="761" alt="Screenshot 2024-11-21 at 1 55 04 PM" src="https://github.com/user-attachments/assets/9160c72a-0adf-4502-aba5-b71d9707ace3">

```

```

**Comment by joewiz** [comment]
Closed by #334.
