### ISSUE TITLE
frus1977-80v29

### ISSUE THREAD

**Issue by mcdanielhn** [HistoryAtState/frus#54]
XML file review for ebooks
- [x] Passes FRUS TEI Schematron check
- [x] Passes RelaxNG schema check
- [x] Scripts run
- [x] Commit schema-compliant file to SVN
- [x] Upload the FRUS TEI file into localhost
- [x] Upload page images to S3
- [x] Typography and characters
- [x] Source note coding
- [x] Table of contents
- [x] Tables, both participant and other
- [x] Openers and assorted segs
- [x] Front matter
- [x] Back matter
- [x] Random sample
- [ ] Volume metadata
- [x] Ebook generation and review

**Comment by WaxCylinderRevival** [comment]
Congrats on progress, @mcdanielhn!

**Comment by mcdanielhn** [comment]
Everything looks good so far, the volume metadata is missing. Also, the hyperlinks in footnotes on the random sample check don't appear to be working. Will follow up on this.

**Comment by mcdanielhn** [comment]
Thanks, @WaxCylinderRevival! #learning
