### ISSUE TITLE
Full titles missing on "Select volumes" page

### ISSUE THREAD

**Issue by awmarrs** [HistoryAtState/frus#55]
On the page for selecting volumes to search:

https://history.state.gov/search/select-volumes

A few volumes have words missing from their complete titles, volume numbers, etc.:

- 	Foreign Relations, Documents on Arms Control and Nonproliferation, 1973-1976

- 	Foreign Relations, 1977–1980, Volume XXVIII, Organization and Management of Foreign Policy

- 	Foreign Relations, 1977–1980, Volume XXIX, Panama, 1977–1980

- 	Foreign Relations of the United States, 1977–1980, Volume XXX

Also, for most of the 1952-1954 sub-series, the years are followed by a period instead of a comma:

	Foreign Relations of the United States, 1952–1954. Indochina (in two parts): Volume XIII, Part 2

**Comment by joewiz** [comment]
@awmarrs Thanks for the report. These and other inconsistencies fixed by https://github.com/HistoryAtState/frus/commit/91c11368a959bb997bc2a1c6af00c7199ebfcd15.

**Comment by awmarrs** [comment]
Thanks, Joe!
