### ISSUE TITLE
Persons IDs

### ISSUE THREAD

**Issue by sd2860** [HistoryAtState/frus#56]
Hi,

I'm currently maintaining and updating the FRUS collection for History Lab at Columbia University, and we're trying to map various person ids across the FRUS volumes to a unique id for each individual, regardless of the different positions they might have held, and the different volumes they may appear in. Since person ids are not unique across the volumes, our approach has been to cluster the names and descriptions and assigning a unique id to each cluster. However, this sometimes leads to wrongly assigning the same id to people with similar names. I was wondering, do you maintain a mapping of all person ids from the volumes to a single id for that person?

**Comment by joewiz** [comment]
@sd2860 Thanks for your question. We have a project in process to de-duplicate the people who appear in FRUS Lists of Persons and unify the IDs assigned to each person. We've completed the de-duplication and assignment of a unique ID to each person, but we have not yet applied the new IDs back onto the data. We have a mapping of new ID to old IDs (and the relevant volumes). See https://github.com/HistoryAtState/people. The service is also live at https://history.state.gov/exist/apps/people. You might also find the slides from a recent presentation useful for background & approach, https://docs.google.com/presentation/d/16k8t4bJsFRunHrQ1sIHOziyJ597MyQQ5KZD8evL3ni4/edit?usp=sharing. The IDs themselves should be persistent, though the final base URL for the person records here may change. Please let us know if you have any questions.
