### ISSUE TITLE
Corrupted mobi file for frus1950v03

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/frus#7]
As reported by a reader to the history_ebooks mailbox, the mobi file for frus1950v03 is corrupt, and needs to be regenerated and uploaded to S3. The link to it on the volume's landing page, https://history.state.gov/historicaldocuments/frus1950v03, shows that the file is 0 bytes. The direct link to the mobi file is https://s3.amazonaws.com/static.history.state.gov/frus/frus1950v03/ebook/frus1950v03.mobi.

**Comment by vak2ve** [comment]
Regenerated and reuploaded

**Comment by joewiz** [comment]
@vak2ve Many thanks!
