### ISSUE TITLE
frus1947v01 errata

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/frus#73]
@vak2ve When you have the chance you please take a look at frus1947v01's "d1" div?  This should be tagged as a front-matter section (`<div type="section" xml:id="errata">`) rather than as document 1; and the `<note>` element here looks incorrect. I think the body documents will need to be renumbered as a result. I haven't checked this against the page images, so it's probably worth confirming this is the correct approach/solution. Here's a screenshot of the section in question:

> ![screen shot 2017-01-23 at 5 08 21 pm](https://cloud.githubusercontent.com/assets/59118/22224960/9eaadbaa-e18e-11e6-9dae-b962f159d730.png)

**Comment by vak2ve** [comment]
@joewiz will fix and renumber docs now--apologies for missing this!

**Comment by joewiz** [comment]
Closed by https://github.com/HistoryAtState/frus/commit/23393e6cd09d8c73e5cb5a295eab24ac3e703144.

Many thanks, Virginia! No worries!
