### ISSUE TITLE
Blank footnote text

### ISSUE THREAD

**Issue by awmarrs** [HistoryAtState/frus#78]
In this document:

https://history.state.gov/historicaldocuments/frus1977-80v18/d129

Clicking on the link in footnote 2 takes you to a page which has only the footnote on it, no additional text:

https://history.state.gov/historicaldocuments/frus1977-80v18/d126fn3

**Comment by joewiz** [comment]
Fixed by https://github.com/HistoryAtState/hsg-shell/commit/87bf7788a6e9a27019ba3ac8a165dcc0da23adb1.
