### ISSUE TITLE
[frus] Reagan administration not showing up in Browse by Administration side bar

### ISSUE THREAD

**Issue by seckroth** [HistoryAtState/frus#9]
https://history.state.gov/historicaldocuments/carter

![screen shot 2016-07-25 at 8 23 01 am](https://cloud.githubusercontent.com/assets/7490970/17101192/2943ada6-5241-11e6-8d03-b57e202a285d.png)

**Comment by joewiz** [comment]
Good eye! Migrated this issue to hsg-shell: https://github.com/eXistSolutions/hsg-shell/issues/243.
