### ISSUE TITLE
Text of 1861 volume missing

### ISSUE THREAD

**Issue by awmarrs** [HistoryAtState/frus#99]
@seckroth I am not sure what is going on here, but the text of the 1861 volume appears to be missing. On the website the title appears, but there is nothing to click on to get the text:

https://history.state.gov/historicaldocuments/frus1861

Thanks,
Aaron

**Comment by joewiz** [comment]
@awmarrs Thanks for spotting this. The servers are a bit in flux at the moment, but I will take care of this when normalcy has been restored.

**Comment by joewiz** [comment]
@seckroth @awmarrs While we have a draft TEI edition of the volume in https://github.com/HistoryAtState/frus-not-yet-reviewed/tree/master/volumes, the volume has not yet been reviewed. I don't believe the text ever was posted. There was a problem - the link to Madison wasn't showing - but this is now fixed. If you need to browse/access this volume or others that haven't been fully reviewed, we can load these up on your computer.

**Comment by awmarrs** [comment]
My apologies, Joe. In my memory, this volume had been fast-tracked for posting even though it was out of sequence. I guess that was just the Lincoln condolences volume? Anyway, thanks for getting the link back up to Madison.
